[package]
name = "probprog_sandbox"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probprog = {path = "../probprog"}
rand = "0.8.5"
rand_distr = "0.4.3"
