[package]
name = "probprog_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
probprog_core = { path = "../probprog_core" }
proc-macro2 = "1.0.47"
syn = { version = "1.0.103", features = ["full", "extra-traits"]}
quote = "1.0.21"
