[package]
name = "probprog"
version = "0.0.0"
edition = "2021"

[dependencies]
probprog_macro = { path = "../probprog_macro" }
probprog_core = { path = "../probprog_core" }
rand = "0.8.5"
rand_distr = "0.4.3"
